stages:
    - build
    - test

build:
    image: gcc
    stage: build

    before_script:
        - apt update
        - apt -y install make cmake libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

    script:
        - cmake .
        - make

    cache:
        untracked: true

test:
    image: gcc
    stage: test

    before_script:
        - apt update
        - apt -y install make cmake libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

    script:
        - cmake .
        - make
        - make test

    cache:
        untracked: true
